### PR TITLE
Support null-safety for dev branch

### PR DESCRIPTION
**Pull request by bhavin-concetto**
I added null-safety to solve [#45](https://github.com/thangmam/smoothratingbar/issues/45)

### CODE REVIEW

**Comment by tomcajot** [comment]
Is there any way I can add this to my flutter project? Thanks.

**Comment by bhavin-concetto** [comment]
@tomcajot You can use it by:
  
smooth_star_rating:
      git:
      url: https://github.com/bhavin-concetto/smoothratingbar.git
      ref: dev

**Comment by tomcajot** [comment]
Great! Thanks

**Review by ladla8602 — APPROVED** [review]

**Comment by bhavin-concetto** [comment]
@thangmam  can you merge this PR?

**Comment by bhavin-concetto** [comment]
@thangmam  dev branch is currently active branch or should I close this PR?

**Comment by thangmam** [comment]
thanks, i have merged it.

**Comment by Gustavoaz** [comment]
Very good, now just need create new version? @thangmam

**Pull request merged**
