### PR TITLE
Support null-safety

### PR DESCRIPTION
**Pull request by leynier**

### CODE REVIEW

**Comment by leynier** [comment]
Fix: #45

**Comment by felixgabler** [comment]
It would be awesome if we could get this merged soon! Thanks!

**Comment by bhavin-concetto** [comment]
@leynier I have fixed #45  with #47. let me know if it is sufficient.

**Comment by bhavin-concetto** [comment]
@leynier  master branch seems not the main branch. "dev" branch is look like updated one. 
@thangmam  can you confirm?

**Comment by benitogonzalezh** [comment]
+1

**Comment by jangruenwaldt** [comment]
+1

**Comment by capriele** [comment]
+1

**Pull request closed without merging**
